### ISSUE TITLE
Assembler Labels generating random address.

### ISSUE THREAD

**Issue by ssarangi** [asmjit/asmjit#93] opened 2015-06-02 23:29 UTC
I have been directly using the assembler to generate code sequences and am seeing an issue which I am not able to figure out if its a bug or if I am doing something wrong.

```
m_pAssembler->mov(m_pAssembler->zax, m_pAssembler->zbx);
saveInsertPoint(&F);
asmjit::Label exitLabel(*m_pAssembler);
m_pAssembler->mov(m_pAssembler->zbx, m_pAssembler->zax);
m_pAssembler->ret(0);
restoreInsertPoint(&F);
m_pAssembler->jmp(exitLabel);
```

This is the code sequence I generate. So what I am unable to understand is what happens when the exit label is created. I see the jmp instruction but its pointing to an address which is garbage and doesn't have the copy back from zax to zbx.

The second issue is that the assembly printing is also incorrect although that my guess is just in the order in which the instructions are added.

  mov rax, rbx
  mov rbx, rax
  ret 0
  jmp L0

---

What I am trying to generate is something like this.

```
   mov rax, rbx
   jmp L0
```

  L0:
       mov rbx, rax
       ret 0

**Comment by kirbyfan64** [comment] 2015-06-02 23:46
You need to "bind" the label:

```c++
m_pAssembler->mov(m_pAssembler->zax, m_pAssembler->zbx);
saveInsertPoint(&F);
asmjit::Label exitLabel(*m_pAssembler);
// bind it
m_pAssembler->bind(exitLabel);
m_pAssembler->mov(m_pAssembler->zbx, m_pAssembler->zax);
m_pAssembler->ret(0);
restoreInsertPoint(&F);
m_pAssembler->jmp(exitLabel);
```

This is to allow for forward references (I think?).

**Comment by ssarangi** [comment] 2015-06-03 02:16
Interesting.. I tried this and it seems to create the label but the address for the jmp is the same as the jmp instruction itself.. For example, this is what Visual Studio displays on its disassembly..

0000005ED95D0000  mov         rax,rbx  
0000005ED95D0003  jmp         0000005ED95D0003 ; The jmp instruction has the same address as the label.  
0000005ED95D0005  add         byte ptr [rax],al  
0000005ED95D0007  add         byte ptr [rax],al  
0000005ED95D0009  add         byte ptr [rax],al  
0000005ED95D000B  add         byte ptr [rax],al

**Comment by kobalicek** [comment] 2015-06-03 08:30
Hi, it's hard to answer without knowing what `saveInsertPoint` and `restoreInsertPoint` do. It seems they delete the code emitted before, which would result in jmp being encoded at position you wanted `mov, rbx, rax`, is that right?

**Comment by ssarangi** [comment] 2015-06-03 15:42
saveInsertPoint & restoreInsertPoint are just wrappers to GetCursor and SetCursor... I will rewrite using those so its clear..

Here is the same sequence rewritten. 

    m_pAssembler->mov(m_pAssembler->zax, m_pAssembler->zbx);
    uint8_t *curPos = m_pAssembler->getCursor();
    asmjit::Label exitLabel(*m_pAssembler);
    // bind it
    m_pAssembler->bind(exitLabel);
    m_pAssembler->mov(m_pAssembler->zbx, m_pAssembler->zax);
    m_pAssembler->ret(0);
    m_pAssembler->setCursor(curPos);
    m_pAssembler->jmp(exitLabel);

**Comment by kobalicek** [comment] 2015-06-03 15:54
1. I would really advice you to not use `setCursor()` - consider using `setOffset()`, which will not crash in case the buffer was reallocated.
2. The `setCursor()` is actually your problem - it moves the current position in code so the `jmp()` will really point to itself. You are basically overwriting your code by doing this.

Maybe if you share more details about your intents I can help you, but `asmjit` behaves as expected in this particular scenario.

**Comment by ssarangi** [comment] 2015-06-03 16:00
I see. So what I am essentially trying to do is very simple. Whenever I see a function I am emitting the prologue for it. After that i create an exit label and generate the epilogue for it. Now what I am trying to do is insert the code for all the other instructions in between. I was thinking of keeping track of the current cursor position of last insertion and then whenever i hit a return i would just add a jmp to the exit label. Kind of how the builder would work but i want to use the assembler directly instead of the compiler class. Does that make sense ?

**Comment by kobalicek** [comment] 2015-06-03 19:08
Well, I understand what you want to do, but this is not the right way of doing that. The problem is that when an instruction is emitted there is a limited way of changing it, it becomes just a series of bytes. Patching is possible, but very limited and dangerous.

In addition, you don't just need to patch, you are basically talking about inserting asm code at certain position, which is currently impossible, and I'm not really planning to support that. I think that what you would need is basically a lightweight version of `Compiler`, but without register allocator and other features.

I will think if there is some way that this could be incorporated to asmjit, basically having a stream of instructions in abstract form (like compiler has) would work, but that would also mean to redesign the architecture a bit (on the other hand it will pretty much allow to disassemble something, alter it, and assemble back).

**Comment by ssarangi** [comment] 2015-06-03 19:35
Right.. that's basically what I wanted to do.. the reason being I was writing the register allocator. I understand the issues with the byte stream and yeah I agree that its a difficult thing to solve. Although I really like the idea you suggest its making me wonder if its too much of redesign for you. I would be glad to help if you have some ideas on this as I am still not very familiar with asmjit's code but let me know if you get some ideas.

**Comment by ssarangi** [comment] 2015-06-04 07:47
Thinking about it more I am leaning towards just keeping the encoded instructions in a linked list rather than an array. The node for the list could store the uint8_t* pointer as well as the number of bytes present. With this we could emulate the builder kind of an interface which could work for inserting instructions in middle as well as reordering instructions. A finalize method could then convert the linkedlist to an array which could be the memory used in the jitter. What do you think ? Would this approach work ? If so I can try out a quick prototype and see. Although there is some performance hit for linked list creation and then traversing it to create the array but it could be made optional i.e based on constructor the container could be decided. Any thoughts ?

**Comment by kobalicek** [comment] 2015-06-04 08:57
I think ideally this shouldn't be part of `Assembler`, but handler by a different class. For example `Compiler` is about 10x slower than `Assembler`, because it has to maintain instructions in abstract form and perform register allocation. Basically I would like to keep `Assembler` slim and fast, and let all the heavy lifting be done outside.

Let me think of this a bit, if I have some idea about the best architecture for this I will let you know.

However, prototyping is fine, you can try :+1:

**Comment by kobalicek** [comment] 2015-06-30 10:26
To add a bit more on this topic. I started some refactoring of asmjit and I think it will be possible to use the instruction stream even without the Compiler, so you would be able to create the stream and manipulate it. But I didn't really finish this work and focus more on Blend atm.

**Comment by kobalicek** [comment] 2015-07-02 18:05
I will close this for now, let's reopen if needed.

**Comment by ssarangi** [comment] 2015-07-02 18:06
sounds good.. let me know if you have some basic implementation :) Thanks a lot for looking into this.

**Comment by kobalicek** [comment] 2015-07-02 18:08
Definitely, I would like to have the instruction stream, let's see if I can cook it in some reasonable time.

**Comment by claytonhotson** [comment] 2016-12-01 07:01
Hello - I have been looking at asmjit, and it is indeed a remarkable piece of work!  Thank you!

I have a similar requirement as ssarangi, where I am producing an prologue and epilogue for a function, but cannot know precisely which instructions to emit into the prologue until the function has been written (I want to avoid a fully 2-pass compilation).  

I have experimented with setOffset() and setCursor() as described, but as ssarangi found, they seem inconsistent (to me anyway!)  

Can you comment on whether you have implemented the changes you mention above, or if you have any recommendations to insert instructions in an earlier section of code?

Thanks so much for any thoughts!

**Comment by kobalicek** [comment] 2016-12-01 08:50
@claytonhotson This functionality is already available in the next branch and the concept is known as `CodeBuilder`, however, I have a lot of code local (not committed) as I'm still completely redesigning the `CodeCompiler`'s register allocator and doing some other tweaks.

The `CodeBuilder` allows to emit instructions to a representation (similarly to `CodeCompiler`) that can be modified on-the-fly, but I guess that already means two-pass. The next branch also contains a function prolog and epilog builder that can be used in a single pass compilation, but in that case you must know which registers will be saved/restored in advance (allows just to change the stack size).

I'm gonna check if this works already so I can create another branch for this (the functionality will be merged with 'next' after I finalize all the work I started)..

**Comment by kobalicek** [comment] 2016-12-01 08:51
I checked the 'next' branch and there the `CodeBuilder` is not fully usable, I need to create another branch for making it available for testing

**Comment by kobalicek** [comment] 2016-12-01 09:03
I have created #146 instead and closing this one, feel free to discuss the `CodeBuilder` concept there

**Closed by kobalicek** 2016-12-01 09:03 UTC
