### ISSUE TITLE
Error in AVX vectorization

### ISSUE THREAD

**Issue by peastman** [asmjit/asmjit#363] opened 2022-04-08 19:46 UTC
I'm trying to track down an error in my program.  I still don't know whether the problem is in my code or in AsmJit, but I've at least narrowed down where it happens.  The following is the simplest demonstration I've been able to come up with.

`generateSingleArgCall()` generates code to invoke a function for every element of a Ymm register and pack the results into another register.  `generateTwoArgCall()` does the same thing for a function that takes two arguments.  In `main()` I create three vectors, `x`, `y`, and `z`, and compute `sinf(y)*powf(y,x)+z`.  At some point during the execution, the upper half of `z` gets cleared.  I store it to memory just before and just after the call to `generateTwoArgCall()` (which doesn't involve `z` in any way) and print them out.  After the call, the upper elements are all zero:

```
3 3 3 3 3 3 3 3 
3 3 3 3 0 0 0 0 
```

But this error only happens when my CI tests are run on Github Actions, and only on Windows.  The Linux and Mac builds work correctly.  I also have tried to reproduce it on local computers under both Windows and Linux, and they work correctly too.  It's only the Github Actions Windows runner that has this problem.

Here is the code.  Do you have any idea what could be going on?

```c++
#include "asmjit/x86.h"
#include <cmath>
#include <cstdio>

using namespace asmjit;
using namespace std;

void generateSingleArgCall(x86::Compiler& c, x86::Ymm& dest, x86::Ymm& arg, float (*function)(float)) {
    x86::Gp fn = c.newIntPtr();
    c.mov(fn, imm((void*) function));
    x86::Ymm a = c.newYmm();
    x86::Ymm d = c.newYmm();
    for (int element = 0; element < 8; element++) {
        if (element < 4)
            c.vshufps(a, arg, arg, imm(element));
        else {
            c.vperm2f128(a, arg, arg, imm(1));
            c.vshufps(a, a, a, imm(element-4));
        }
        InvokeNode* invoke;
        c.invoke(&invoke, fn, FuncSignatureT<float, float>());
        invoke->setArg(0, a);
        invoke->setRet(0, d);
        if (element > 3)
            c.vperm2f128(d, d, d, imm(0));
        if (element != 0)
            c.vshufps(d, d, d, imm(0));
        c.vblendps(dest, dest, d, 1<<element);
    }
}

void generateTwoArgCall(x86::Compiler& c, x86::Ymm& dest, x86::Ymm& arg1, x86::Ymm& arg2, float (*function)(float, float)) {
    x86::Gp fn = c.newIntPtr();
    c.mov(fn, imm((void*) function));
    x86::Ymm a1 = c.newYmm();
    x86::Ymm a2 = c.newYmm();
    x86::Ymm d = c.newYmm();
    for (int element = 0; element < 8; element++) {
        if (element < 4) {
            c.vshufps(a1, arg1, arg1, imm(element));
            c.vshufps(a2, arg2, arg2, imm(element));
        }
        else {
            c.vperm2f128(a1, arg1, arg1, imm(1));
            c.vperm2f128(a2, arg2, arg2, imm(1));
            c.vshufps(a1, a1, a1, imm(element-4));
            c.vshufps(a2, a2, a2, imm(element-4));
        }
        InvokeNode* invoke;
        c.invoke(&invoke, fn, FuncSignatureT<float, float, float>());
        invoke->setArg(0, a1);
        invoke->setArg(1, a2);
        invoke->setRet(0, d);
        if (element > 3)
            c.vperm2f128(d, d, d, imm(0));
        if (element != 0)
            c.vshufps(d, d, d, imm(0));
        c.vblendps(dest, dest, d, 1<<element);
    }
}

void storeReg(x86::Compiler& c, x86::Ymm& reg, float* dest) {
    x86::Gp ptr = c.newIntPtr();
    c.mov(ptr, imm(dest));
    c.vmovdqu(x86::ptr(ptr, 0, 0), reg);
}

int main() {
    // Set up the compiler.

    JitRuntime runtime;
    CodeHolder code;
    code.init(runtime.environment());
    x86::Compiler c(&code);
    FuncNode* funcNode = c.addFunc(FuncSignatureT<void>());
    funcNode->frame().setAvxEnabled();

    // Load variables.

    float x[] = {1, 1, 1, 1, 1, 1, 1, 1};
    float y[] = {2, 2, 2, 2, 2, 2, 2, 2};
    float z[] = {3, 3, 3, 3, 3, 3, 3, 3};
    x86::Ymm xreg = c.newYmmPs();
    x86::Ymm yreg = c.newYmmPs();
    x86::Ymm zreg = c.newYmmPs();
    x86::Gp xptr = c.newIntPtr();
    x86::Gp yptr = c.newIntPtr();
    x86::Gp zptr = c.newIntPtr();
    c.mov(xptr, imm(x));
    c.mov(yptr, imm(y));
    c.mov(zptr, imm(z));
    c.vmovdqu(xreg, x86::ptr(xptr, 0, 0));
    c.vmovdqu(yreg, x86::ptr(yptr, 0, 0));
    c.vmovdqu(zreg, x86::ptr(zptr, 0, 0));

    // Perform the computation.

    float z1[8], z2[8];
    x86::Ymm siny = c.newYmmPs();
    generateSingleArgCall(c, siny, yreg, sinf);
    storeReg(c, zreg, z1);
    x86::Ymm powyx = c.newYmmPs();
    generateTwoArgCall(c, powyx, yreg, xreg, powf);
    storeReg(c, zreg, z2);
    x86::Ymm prod = c.newYmmPs();
    c.vmulps(prod, siny, powyx);
    x86::Ymm sum = c.newYmmPs();
    c.vaddps(sum, prod, zreg);
    c.endFunc();
    c.finalize();
    void (*jitCode)();
    runtime.add(&jitCode, &code);

    // Execute it.

    jitCode();
    for (int i = 0; i < 8; i++)
        printf("%g ", z1[i]);
    printf("\n");
    for (int i = 0; i < 8; i++)
        printf("%g ", z2[i]);
    printf("\n");
    return 0;
}
```

**Comment by kobalicek** [comment] 2022-04-08 20:59
I think this is 99% bug on AsmJit side. The problem is most likely AsmJit is keeping content of YMM registers across the function call, which it shouldn't as Windows calling convention can clobber the upper half of the registers (most likely it calls `vzeroupper`).

**Comment by peastman** [comment] 2022-04-08 21:37
Good to know it's not just me being crazy. :)  Let me know if you need help testing the fix.

**Comment by kobalicek** [comment] 2022-04-09 22:14
@peastman Can you test `dead_movs` branch? It contains more RA changes, I just added the fix there as I plan to merge it.

**Comment by peastman** [comment] 2022-04-09 23:36
Works perfectly.  Thanks, you're amazing!

**Comment by kobalicek** [comment] 2022-04-10 08:10
Fix was merged, thanks for the report!

**Closed by kobalicek** 2022-04-10 08:10 UTC
