### ISSUE TITLE
Trampolines for conditional jumps?

### ISSUE THREAD

**Issue by Nekotekina** [asmjit/asmjit#198] opened 2018-04-16 17:24 UTC
Hello, I noticed that ja/jb/etc instructions allow Imm argument, and thus `imm_ptr()`.
I see that on x86-64, jmp with `imm_ptr` produces trampoline correctly if necessary.
However, it's not possible in the case of conditional jumps, they silently generate invalid code.

Possibly improve trampolines for conditional jumps? Could be solved by emitting additional jmp instruction implicitly somewhere at the end of function.

**Comment by kobalicek** [comment] 2018-04-16 17:45
Well I think this is a misuse as these imm forms for conditional jumps were mostly introduced for emitting instructions with relative displacement in case that the address of that instruction is already known (I mean code generation with known base address). However, if asmjit accepts it without a failure and encodes wrong binary then it's a bug as well. 

On the other side I have never seen conditional jumps used with trampolines, but the suggested approach would work. I'm currently finishing a first version of my other project so I'm not sure I can fix this atm, but I would definitely at least check what asmjit does, because I don't want it to emit wrong asm.

**Comment by Nekotekina** [comment] 2018-04-17 05:32
How can I check, whether I can reach destination with conditional jump safely, if it's another function? It's 99,9% success because they belong to the same runtime, but remaining little chance forces to always emit jmp, losing this little "optimization" chance. Although it's a violation of a calling convention, I don't see how it can hurt.

**Comment by kobalicek** [comment] 2018-04-17 13:19
Well there are basically two cases

  - The destination is some address that was already allocated by JIT allocator (so it's some function you already generated)
  - The destination is something else, for example some C/other library function.

In the first case the chance you hit 32-bit displacement is likely unless the JIT allocator allocates some region that is far from it. Since JIT allocator allocates memory in larger blocks this could be gambling as you simply cannot know if the next block will be close enough or not (I mean what a successive call to `mmap` or `VirtualAlloc` would return). The only way to make this case more likely would be to increase the block size of JIT allocated memory - for example if you increase it to 128 MB, and you know you will never emit more than 128MB the chance the jump would be encodable as +-2GB relative displacement is 100%.

If you are jumping to some library function then I would discourage of using conditional jumps in this case as all as it's simply not the preferred way of doing this.

I mean I'm pretty positive with changing asmjit to allow this as conditional jump level, I just need to find some time to go and implement it (preferably in next-wip as I would not really work on master branch if it's not some critical issue).

**Comment by ZehMatt** [comment] 2018-05-04 09:16
I think the issue is because you'll find data for the address after the jcc where with a jmp this isn't an issue. However this situation could be easily defused by prepending EB imm8 before the address data if the previous instruction is a conditional jump.

**Comment by kobalicek** [comment] 2020-08-31 18:42
Any objections against closing this one? It's open for a while and I'm not so sure about it. For me jmp/call are enough to use address-table.

**Closed** 2020-09-01 21:08 UTC
