### ISSUE TITLE
What's the point of VirtualAllocEx and VirtualFreeEx in vmem.cpp

### ISSUE THREAD

**Issue by PELock** [asmjit/asmjit#131] opened 2016-06-02 21:01 UTC
Hmm, I don't follow, why do you need those functions if you pass the current process handle to them.

Can't you just use VirtualAlloc & VirtualFree? Why overcomplicate things?

```
#if !defined(ASMJIT_OS_WINDOWS)
  return static_cast<uint8_t*>(VMemUtil::alloc(size, vSize, flags));
#else
  return static_cast<uint8_t*>(VMemUtil::allocProcessMemory(self->_hProcess, size, vSize, flags));
#endif 

+

void* VMemUtil::alloc(size_t length, size_t* allocated, uint32_t flags) {
  return allocProcessMemory(static_cast<HANDLE>(0), length, allocated, flags);
} 

+

static const VMemLocal& vMemGet() {
  VMemLocal& vMem = vMemLocal;

  if (!vMem.hProcess) {
    SYSTEM_INFO info;
    ::GetSystemInfo(&info);

    vMem.pageSize = IntUtil::alignToPowerOf2<uint32_t>(info.dwPageSize);
    vMem.pageGranularity = info.dwAllocationGranularity;

    vMem.hProcess = ::GetCurrentProcess();
  }
 

```

So on anything else than Windows you don't need *YOUR OWN* process handle, but suddenly on Windows you need it?

**Comment by kobalicek** [comment] 2016-06-02 21:11
This is used for remote code injection - in that case you supply a handle of a different process, where the memory will be allocated and that pointer will be used as a base address. Then by using `WriteProcessMemory()` you can actually write assembled code into that process's memory. This functionality just simplifies the injection as the memory manager can be used to manage memory of a different process.

I have no clue how this would be done on Windows, never tried on non-windows platform.

**Comment by PELock** [comment] 2016-06-02 21:25
But I don't need this :panda_face: it broke compatibility with the ancient Win versions of my app and I keep it compatible as a point of honour :smiling_imp: and the only thing that broke this compatibility was those 2 functions in AsmJit because of some obscure features (show me 1 project that uses it) :smile: 

Also tried this new version from GitHub on my old VS2003 (again, compatibility reasons) and I see you just don't care anymore :disappointed:

**Comment by kirbyfan64** [comment] 2016-06-02 21:26
Well, there *does* come a point where maintaining compatibility with compilers over a decade old becomes cumbersome...

**Comment by PELock** [comment] 2016-06-02 21:27
I don't care, I like my software compatible across all versions of Windows and this is C++ after all, do I really need Windows 10 to run my C++ code?

**Comment by kirbyfan64** [comment] 2016-06-02 21:58
> I don't care, I like my software compatible across all versions of Windows and this is C++ after all, do I really need Windows 10 to run my C++ code?

Huh? All you need to run it is the VC++ 2015 runtime, which even runs on XP. You don't need Windows 10.

**Comment by PELock** [comment] 2016-06-02 22:08
How about compiling code without those extra 2 functions and without installing extra runtime libraries? I like this solution better, if you like bloatware code with useless API functions, tons of runtime packages - it's your choice buddy. Someone said AsmJit has become a bloatware and by looking at

https://github.com/kobalicek/asmjit/blob/master/src/asmjit/build.h

or this vmem.cpp mess, I can't disagree... sorry Petr.

**Comment by kobalicek** [comment] 2016-06-02 22:14
I definitely care! But I don't have any continuous integration where I can try if asmjit breaks on something else than I'm using. The problem is that now I don't even use Windows on a daily basis, so I guess the issue is more likely how to properly test asmjit on various windows' configurations, as Linux and MacOS are tested properly.

However, I'm not sure if the `VirtualAlloxEx`is really the issue here. I'm using it from the beginning as it was recommended somewhere (hard to recall the original intention though) when I started with JIT. It's supported by WinXP and Win2003 Server, that's an amazing backward compatibility feature I think.

But if you know anything that prevents compiling asnhut on older compilers you can let me know, but as I said, I don't have these old tools to test it properly and I have developed an extensive compile-feature detection called cxxtool (https://github.com/kobalicek/cxxtool) that I use to manage all my projects and to keep them backward compatible with older tools.

**Comment by PELock** [comment] 2016-06-02 22:21
Petr you have hundreds of compatibility settings in build.h (config.h previously) and you say all of this is useless? I don't even know what to say... what's the point if it doesn't work?

This VirtualAllocEx() is not a problem, I've already fixed it for my needs (replaced it with VirtualAlloc and removed the hProcess parameter).

**Comment by kobalicek** [comment] 2016-06-02 23:40
I didn't say that. I think that asmjit backwards compatibility is very good compared to most projects that nowaday just use c++11 and require the newest c++ compiler to be compiled. And I offered you help to make it working, so why that bad tone?

**Comment by nelson2005** [comment] 2016-06-03 02:03
Dude's a troll.  Asmjit is the least bloated project I've seen, keep up the good work!
On Jun 2, 2016 6:08 PM, Bartosz Wójcik <notifications@github.com> wrote:How about compiling code without those extra 2 functions and without installing extra runtime libraries? I like this solution better, if you like bloatware code with useless API functions, tons of runtime packages - it's your choice buddy. Someone said AsmJit has become a bloatware and by looking at

https://github.com/kobalicek/asmjit/blob/master/src/asmjit/build.h

or this vmem.cpp mess, I can't disagree... sorry Petr.

**Comment by kobalicek** [comment] 2016-08-06 19:21
Guys I'm closing this as this discussion is not constructive.

I will still support pre C++0x compilers (through cxxtool) and WinXP+, but I will not support by default Win2000 and older Windows operating systems. Anyone is free to have its own fork. In asmjit:next branch I have reorganized platform dependent code and I have put everything to osutils.h and osutils.cpp, to make possible porting to other platform and maintaining zombies easier.

**Closed by kobalicek** 2016-08-06 19:21 UTC
Labels: wontfix
