### ISSUE TITLE
Do not donate to this project!

### ISSUE THREAD

**Issue by PELock** [asmjit/asmjit#233] opened 2019-01-26 23:50 UTC
Hello Petr,

I thought you would do the right thing and put my name on the donors
list, because I have proven the donations were paid without asking for
anything in return, I show you the email where you came up with that
idea yourself to put my link on your project site!

If you are such a fu*king **stubborn prick and can't admit to the
wrongdoing and swallow your pride**, either put my name on the donors
list since I was a donor 4 frickin times and I deserve to be there or
if it hurts your feeling so deeply to admit I was your first supporter,
return the money, I would gladly donate it to the animal shelter
instead of supporting someone as ungrateful as you.

**Comment by kobalicek** [comment] 2019-01-27 00:04
Duplicate of #231

**Comment by ZehMatt** [comment] 2019-01-27 07:09
Out of curiosity, why do you want your name on the front page so badly? Lets not forget that you are using asmjit in your paid software and you should be rather thankful that such project exists and one that probably saved you a lot of effort to write your own x86 encoder, given how many hours were put into asmjit by Petr you still have the nerve to complain. Your behavior is absolutely childish and I rather see you write a blog post or go somewhere else instead of spamming issues on GitHub, also 125€ is not that much, I know its not nothing but you should probably consider that you are not getting the golden spoon for this, I've probably donated 10 times your amount and I can swallow my name being removed, if it gets removed, donations usually come with no obligations, so if you want Petrs full attention and all your issues with asmjit fixed right away like you would get with SaaS then I recommend you talk out a business proposal instead, your way isn't helping anyone and will get you absolutely no where.

**Comment by PELock** [comment] 2019-01-27 14:02
It was there for years and suddenly he removed it. Maybe he thought I didn't notice or care, well I do, I was proud I have supported this project and I think my name there is nothing big - overall it's just a name on the donors list, not a golden spoon, don't exaggerate it.

But this simple gesture of kindness is too much for Petr obviously, isn't it?

So your name was removed too? Don't you think this is pretty low?

1. He takes donations
2. He lists the donors
3. He removes the donors from the list
4. What's the point of keeping donors list?

I've never seen something like this in any other project accepting donations, once you donate you are listed - case closed.

You need to me real **ungrateful prick to remove your donors from the donation list**. That's my whole point.

**Comment by kirbyfan64** [comment] 2019-01-27 14:04
I can't even afford to donate, yet I'm finding this complaint that I quite frankly don't care about in my notifications. ¯\\\_(ツ)\_/¯

**Comment by PELock** [comment] 2019-01-27 14:06
Good. People should see how Petr Kobalicek treats his supporters, by secretly removing them from the donation list.

**Comment by ZehMatt** [comment] 2019-01-27 14:21
Perhaps next time you should discuss such things with the entity in question what a donation means and what kind of benefits you would receive, I doubt it was ever promised to keep the names forever.

**Comment by PELock** [comment] 2019-01-27 14:35
@ZehMatt I did. I didn't expect anything in return. Petr posted my name and link to my site himself.

@kazet88 yeah, one would think this would solve the case, but it's TOO MUCH for Petr, he is too stubborn and too proud to admit he took the money when he need it and now when he obviously has the money - he doesn't care about people who supported him when he was dead broke.

**Comment by yzrmn** [comment] 2019-01-27 14:57
@kazet88 May I ask, what is your affiliation with the project?

> he is too stubborn and too proud to admit he took the money when he need it and now when he obviously has the money

He said in #231 that he didn't work on AsmJit for money and I especially quote @kobalicek on this

> I love sharing my work and I don't demand anything in return.

But you are obviously hostile against everyone who doesn't share your opinion and try to escalate it to the highest level. If you were really interested in having a civilized discussion you would first try to solve with private communication. This obviously happened after you opened #231, however obviously with no resolution. And now you are creating a new issue after you had one week to comment on the old one.

> I didn't expect anything in return. Petr posted my name and link to my site himself.

Then what's the problem now?

**Comment by kobalicek** [comment] 2019-01-27 15:04
@PELock

There are people that are seriously watching this project in intention to either help others or get help and you are making the life of them uncomfortable. I have already asked you many times to stop and you never listened. As Matt said, move this crusade against me into your blog or your company's homepage, but out of here, because you are seriously close from getting banned. I really think that I have already given you enough audience and attention here and it's time to stop it.

You offended me many times yet I stayed calm and offered you a solution that I thought was the best for both - and since you sent me the IBAN I thought you accepted my offer to return you the donation so we both can part ways. So I don't understand why you have to open another issue and ventilate yourself here again. The fact that you tried to hurt me through my project is an act of cowardice and based on everything that you sent me privately and publicly I'm not willing to put your name on the front. It seems that you are used to offend people around you to get what you want, but believe me I'm not used to that and I find it unacceptable.

**Comment by PELock** [comment] 2019-01-27 15:41
You wasn't too keen to solve this matter neither in our email communication or here. With a simple thing - restore the donors list.

I hope people can read this how you handle the donations by taking the money, adding donors to the page and then **secretly** removing them like it's nothing to you.

I told you either to either restore the donors list or return the money if you are too stubborn. It's foolish and childish on your side to remove this information from your page if you have accepted the donations first when you were broke.

The choice is yours. Be a man and do what's right and I won't bother you again, because right now I feel you have cheated me and other donors.

**Comment by kazet88** [comment] 2019-01-27 15:50
@yzrmn and who are you? I am a donor.

It is disgusting that Petr is not able to respect the fact that someone gave him hard earned money.

Shame on you Petr.

**Comment by kobalicek** [comment] 2019-01-27 15:57
@kazet88 Are you? Maybe by revealing your real name I would be able to confirm that claim, otherwise I cannot.

**Comment by yzrmn** [comment] 2019-01-27 15:57
> I told you either to either restore the donors list or return the money if you are too stubborn.

No, you did not. If that were the case, this issue would not exist. He did offer this to you multiple times in #231 and you didn't want it.

> Keep the money, but you have lost my respect.

> Keep the money, you deserve it, [...]

> So keep the money, forget about me, I will remove the comment from GitHub.

**Comment by PELock** [comment] 2019-01-27 16:04
@yzrmn I didn't ask you for your opinion, are you his attorney?

I thought he would man up and restore the donors list like an adult would do.

He decided to close this case, remove the donations list and hide this discussion from the audience.

**Comment by kobalicek** [comment] 2019-01-27 16:05
If you didn't want audience then why you opened this issue?

**Comment by PELock** [comment] 2019-01-27 16:09
To make you feel bad you cheated me and other donors. Because it seems you have no regrets.

**Comment by kobalicek** [comment] 2019-01-27 16:10
I'm not your boyfriend to cheat on you.

**Comment by PELock** [comment] 2019-01-27 16:11
"cheated me" vs "cheated on me"

I'm glad people can see this.

**Comment by yzrmn** [comment] 2019-01-27 16:33
> I've heard it a few times in the past asmjit is a bloated nightmare and people are using more effective solutions in their software.

Well, you are free to fork the project, make changes and fix those bugs as you see fit.

**Comment by zerotri** [comment] 2019-01-27 18:13
Since this is still continuing to drag on.

Let me point you to this page: https://help.github.com/articles/github-community-guidelines/

In particular, the section that states
`Bullying and harassment - We do not tolerate bullying or harassment. This means any habitual badgering or intimidation targeted at a specific person or group of people. In general, if your actions are unwanted and you continue to engage in them, there's a good chance you are headed into bullying or harassment territory.`

I'm fairly certain this counts as harassment at this point. Especially if your motive is
`To make you feel bad you cheated me and other donors. Because it seems you have no regrets.`

If you disagree with how the project is run or the direction the code is going, fork it. Open source developers are not here to serve your every whim. @kobalicek has a life beyond asmjit, one that a few small donations isn't changing drastically. He has provided asmjit to us for free, a project which has taken many hours of his time. He does not work for you. Your choice to donate should be thought of as a kindness and nothing more. A simple thanks from you to the author.

This behaviour here is equivalent to a childish tantrum. Accept the return of your donation, or don't. Move on. There is no reason to continue with this.

**Comment by kazet88** [comment] 2019-01-27 21:13
He has a strong fan-base from what I can see and they aren't bothered by the wrongdoings of their god.

I'm so surprised more people aren't offended by the behaviour of mr Kobalicek.

**Comment by kobalicek** [comment] 2019-01-27 22:43
I would like to ask @PELock and @kazet88 to either stop the conversation here or to move it to some other site. PELock's donation was returned, animal shelter was supported as a bonus, and I have nothing else to say except thanking others for calm and supportive attitude.

I hope we can finally move on and focus on coding instead of wasting time on this.

**Closed by kobalicek** 2019-01-27 22:43 UTC
