### ISSUE TITLE
Zone allocated objects are sometimes misaligned (Zone usage bug)

### ISSUE THREAD

**Issue by Hades0299** [asmjit/asmjit#176] opened 2017-07-27 10:45 UTC
While debugging an error in in application I write, where I got diffrent results depending on the buildtype. I noticed, that the alloc-function within zone.h cannot handle alignement to specified boundaries.
Is this intentional? Or is there something depending on the fact, that there is no space between the allocated parts?

To reproduce the warnings, you need to compile this with `gcc  -fsanitize=undefined` and execute the binary.
Regards
Hades

**Comment by kobalicek** [comment] 2017-07-27 11:00
I'm not sure what the problem is at the moment, and I haven't noticed any problem regarding this, do you think you can be more specific? I can check out the sanitizer, maybe it would be a good idea to use it on CI.

**Comment by kobalicek** [comment] 2017-07-27 11:09
Or do you mean Zone returns unaligned memory?

**Comment by Hades0299** [comment] 2017-07-27 12:05
Yes, zone returns unaligned memory.
one of the messages is:
`/src/asmjit/base/../base/constpool.h:167:31: runtime error: member access within misaligned address 0x000000cbdad2 for type 'Node *[2]', which requires 8 byte alignment
0x000000cbdad2: note: pointer points here
 6e 73  74 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00`

in the line 167 in constpool.h a new node gets its members initialized with nullptr. This node gets allocated earlier (line 164) with zone->allocT(...), that returns unaligned memory, so the members are not necessarily aligned.

Sry, I didnt provide this information earlier.
Hades

**Comment by kobalicek** [comment] 2017-07-27 12:07
Okay I see, yeah, I think this is a bug and I will fix it.

**Comment by Hades0299** [comment] 2017-07-27 12:29
Great to hear, and thanks for the title-clarification :)

Regards
Hades

**Comment by kobalicek** [comment] 2017-07-27 13:40
You are welcome, I will first try to enable this at CI level, then fix, be patient a bit as I'm now working on asmjit-wip

**Comment by kobalicek** [comment] 2017-08-15 20:35
I have this already fixed in my local wip branch. I expect maybe one week before I commit these changes.

**Comment by Hades0299** [comment] 2017-08-16 06:08
Thanks, i'm looking forward to it.

**Comment by kobalicek** [comment] 2017-08-21 17:26
Already fixed in next-wip branch. I will see if it makes sense to backport to master. Honestly, I would like to just wait until next-wip is merged (not possible atm as the compiler infrastructure is still not working properly).

**Comment by Hades0299** [comment] 2017-09-14 12:24
Are there any news regarding next-WIP?
If you need help, you could commit what you have and I or others could help figure things out.

Regards,
Hades

**Comment by kobalicek** [comment] 2017-09-17 13:37
I will commit the related work soon, still finalizing one more feature that I need before updating the branch.

**Comment by kobalicek** [comment] 2019-07-15 23:55
Closing as next-wip was merged.

**Closed by kobalicek** 2019-07-15 23:55 UTC
Labels: bug, next-ready
