### ISSUE TITLE
asmjit accepts instructions with invalid operand size combinations

### ISSUE THREAD

**Issue by mappzor** [asmjit/asmjit#226] opened 2018-12-05 22:27 UTC
I found out that for some instructions asmjit doesn't detect impossible combinations of operands. In all cases shown below asmjit reports no errors and happily generates instructions with same size operands. Expected behavior would be error kErrorOperandSizeMismatch which I received in several other instructions tested (few examples: adc, add, or, sub, xor).

Here's code for reproduction:
```c
asmjit::Error gen_bt_op0_reg_bx_op1_reg_edx(asmjit::X86Assembler &a)
{
	asmjit::Operand op[2];
	op[0] = asmjit::x86::bx;
	op[1] = asmjit::x86::edx;
	return a.emit(asmjit::X86Inst::kIdBt, op[0], op[1]);
}

asmjit::Error gen_bt_op0_reg_ebx_op1_reg_dx(asmjit::X86Assembler &a)
{
	asmjit::Operand op[2];
	op[0] = asmjit::x86::ebx;
	op[1] = asmjit::x86::dx;
	return a.emit(asmjit::X86Inst::kIdBt, op[0], op[1]);
}

asmjit::Error gen_btc_op0_reg_bx_op1_reg_edx(asmjit::X86Assembler &a)
{
	asmjit::Operand op[2];
	op[0] = asmjit::x86::bx;
	op[1] = asmjit::x86::edx;
	return a.emit(asmjit::X86Inst::kIdBtc, op[0], op[1]);
}

asmjit::Error gen_btc_op0_reg_ebx_op1_reg_dx(asmjit::X86Assembler &a)
{
	asmjit::Operand op[2];
	op[0] = asmjit::x86::ebx;
	op[1] = asmjit::x86::dx;
	return a.emit(asmjit::X86Inst::kIdBtc, op[0], op[1]);
}

asmjit::Error gen_btr_op0_reg_bx_op1_reg_edx(asmjit::X86Assembler &a)
{
	asmjit::Operand op[2];
	op[0] = asmjit::x86::bx;
	op[1] = asmjit::x86::edx;
	return a.emit(asmjit::X86Inst::kIdBtr, op[0], op[1]);
}

asmjit::Error gen_btr_op0_reg_ebx_op1_reg_dx(asmjit::X86Assembler &a)
{
	asmjit::Operand op[2];
	op[0] = asmjit::x86::ebx;
	op[1] = asmjit::x86::dx;
	return a.emit(asmjit::X86Inst::kIdBtr, op[0], op[1]);
}

asmjit::Error gen_bts_op0_reg_bx_op1_reg_edx(asmjit::X86Assembler &a)
{
	asmjit::Operand op[2];
	op[0] = asmjit::x86::bx;
	op[1] = asmjit::x86::edx;
	return a.emit(asmjit::X86Inst::kIdBts, op[0], op[1]);
}

asmjit::Error gen_bts_op0_reg_ebx_op1_reg_dx(asmjit::X86Assembler &a)
{
	asmjit::Operand op[2];
	op[0] = asmjit::x86::ebx;
	op[1] = asmjit::x86::dx;
	return a.emit(asmjit::X86Inst::kIdBts, op[0], op[1]);
}

asmjit::Error gen_imul_op0_reg_bx_op1_reg_edx_op2_simm_0000BBBB(asmjit::X86Assembler &a)
{
	asmjit::Operand op[3];
	op[0] = asmjit::x86::bx;
	op[1] = asmjit::x86::edx;
	op[2] = asmjit::Imm(0x0000BBBB);
	return a.emit(asmjit::X86Inst::kIdImul, op[0], op[1], op[2]);
}

asmjit::Error gen_imul_op0_reg_bx_op1_reg_edx_op2_simm_CCCCCCCC(asmjit::X86Assembler &a)
{
	asmjit::Operand op[3];
	op[0] = asmjit::x86::bx;
	op[1] = asmjit::x86::edx;
	op[2] = asmjit::Imm(0xCCCCCCCC);
	return a.emit(asmjit::X86Inst::kIdImul, op[0], op[1], op[2]);
}

asmjit::Error gen_imul_op0_reg_ebx_op1_reg_dx_op2_simm_0000BBBB(asmjit::X86Assembler &a)
{
	asmjit::Operand op[3];
	op[0] = asmjit::x86::ebx;
	op[1] = asmjit::x86::dx;
	op[2] = asmjit::Imm(0x0000BBBB);
	return a.emit(asmjit::X86Inst::kIdImul, op[0], op[1], op[2]);
}

asmjit::Error gen_imul_op0_reg_ebx_op1_reg_dx_op2_simm_CCCCCCCC(asmjit::X86Assembler &a)
{
	asmjit::Operand op[3];
	op[0] = asmjit::x86::ebx;
	op[1] = asmjit::x86::dx;
	op[2] = asmjit::Imm(0xCCCCCCCC);
	return a.emit(asmjit::X86Inst::kIdImul, op[0], op[1], op[2]);
}

asmjit::Error gen_imul_op0_reg_bx_op1_reg_edx_op2_simm_000000AA(asmjit::X86Assembler &a)
{
	asmjit::Operand op[3];
	op[0] = asmjit::x86::bx;
	op[1] = asmjit::x86::edx;
	op[2] = asmjit::Imm(0x000000AA);
	return a.emit(asmjit::X86Inst::kIdImul, op[0], op[1], op[2]);
}

asmjit::Error gen_imul_op0_reg_ebx_op1_reg_dx_op2_simm_000000AA(asmjit::X86Assembler &a)
{
	asmjit::Operand op[3];
	op[0] = asmjit::x86::ebx;
	op[1] = asmjit::x86::dx;
	op[2] = asmjit::Imm(0x000000AA);
	return a.emit(asmjit::X86Inst::kIdImul, op[0], op[1], op[2]);
}

asmjit::Error gen_shld_op0_reg_bx_op1_reg_edx_op2_uimm_000000AA(asmjit::X86Assembler &a)
{
	asmjit::Operand op[3];
	op[0] = asmjit::x86::bx;
	op[1] = asmjit::x86::edx;
	op[2] = asmjit::Imm(0x000000AA);
	return a.emit(asmjit::X86Inst::kIdShld, op[0], op[1], op[2]);
}

asmjit::Error gen_shld_op0_reg_ebx_op1_reg_dx_op2_uimm_000000AA(asmjit::X86Assembler &a)
{
	asmjit::Operand op[3];
	op[0] = asmjit::x86::ebx;
	op[1] = asmjit::x86::dx;
	op[2] = asmjit::Imm(0x000000AA);
	return a.emit(asmjit::X86Inst::kIdShld, op[0], op[1], op[2]);
}

asmjit::Error gen_shld_op0_reg_bx_op1_reg_edx_op2_reg_cl(asmjit::X86Assembler &a)
{
	asmjit::Operand op[3];
	op[0] = asmjit::x86::bx;
	op[1] = asmjit::x86::edx;
	op[2] = asmjit::x86::cl;
	return a.emit(asmjit::X86Inst::kIdShld, op[0], op[1], op[2]);
}

asmjit::Error gen_shld_op0_reg_ebx_op1_reg_dx_op2_reg_cl(asmjit::X86Assembler &a)
{
	asmjit::Operand op[3];
	op[0] = asmjit::x86::ebx;
	op[1] = asmjit::x86::dx;
	op[2] = asmjit::x86::cl;
	return a.emit(asmjit::X86Inst::kIdShld, op[0], op[1], op[2]);
}

asmjit::Error gen_shrd_op0_reg_bx_op1_reg_edx_op2_uimm_000000AA(asmjit::X86Assembler &a)
{
	asmjit::Operand op[3];
	op[0] = asmjit::x86::bx;
	op[1] = asmjit::x86::edx;
	op[2] = asmjit::Imm(0x000000AA);
	return a.emit(asmjit::X86Inst::kIdShrd, op[0], op[1], op[2]);
}

asmjit::Error gen_shrd_op0_reg_ebx_op1_reg_dx_op2_uimm_000000AA(asmjit::X86Assembler &a)
{
	asmjit::Operand op[3];
	op[0] = asmjit::x86::ebx;
	op[1] = asmjit::x86::dx;
	op[2] = asmjit::Imm(0x000000AA);
	return a.emit(asmjit::X86Inst::kIdShrd, op[0], op[1], op[2]);
}

asmjit::Error gen_shrd_op0_reg_bx_op1_reg_edx_op2_reg_cl(asmjit::X86Assembler &a)
{
	asmjit::Operand op[3];
	op[0] = asmjit::x86::bx;
	op[1] = asmjit::x86::edx;
	op[2] = asmjit::x86::cl;
	return a.emit(asmjit::X86Inst::kIdShrd, op[0], op[1], op[2]);
}

asmjit::Error gen_shrd_op0_reg_ebx_op1_reg_dx_op2_reg_cl(asmjit::X86Assembler &a)
{
	asmjit::Operand op[3];
	op[0] = asmjit::x86::ebx;
	op[1] = asmjit::x86::dx;
	op[2] = asmjit::x86::cl;
	return a.emit(asmjit::X86Inst::kIdShrd, op[0], op[1], op[2]);
}

#define TEST(name) { #name, gen_ ## name }

typedef asmjit::Error (*gen_t)(asmjit::X86Assembler &a);

struct TestData
{
	const char *name;
	gen_t gen;
};

void test()
{
	TestData tests[] = {
		TEST(bt_op0_reg_bx_op1_reg_edx),
		TEST(bt_op0_reg_ebx_op1_reg_dx),
		TEST(btc_op0_reg_bx_op1_reg_edx),
		TEST(btc_op0_reg_ebx_op1_reg_dx),
		TEST(btr_op0_reg_bx_op1_reg_edx),
		TEST(btr_op0_reg_ebx_op1_reg_dx),
		TEST(bts_op0_reg_bx_op1_reg_edx),
		TEST(bts_op0_reg_ebx_op1_reg_dx),
		TEST(imul_op0_reg_bx_op1_reg_edx_op2_simm_0000BBBB),
		TEST(imul_op0_reg_bx_op1_reg_edx_op2_simm_CCCCCCCC),
		TEST(imul_op0_reg_ebx_op1_reg_dx_op2_simm_0000BBBB),
		TEST(imul_op0_reg_ebx_op1_reg_dx_op2_simm_CCCCCCCC),
		TEST(imul_op0_reg_bx_op1_reg_edx_op2_simm_000000AA),
		TEST(imul_op0_reg_ebx_op1_reg_dx_op2_simm_000000AA),
		TEST(shld_op0_reg_bx_op1_reg_edx_op2_uimm_000000AA),
		TEST(shld_op0_reg_ebx_op1_reg_dx_op2_uimm_000000AA),
		TEST(shld_op0_reg_bx_op1_reg_edx_op2_reg_cl),
		TEST(shld_op0_reg_ebx_op1_reg_dx_op2_reg_cl),
		TEST(shrd_op0_reg_bx_op1_reg_edx_op2_uimm_000000AA),
		TEST(shrd_op0_reg_ebx_op1_reg_dx_op2_uimm_000000AA),
		TEST(shrd_op0_reg_bx_op1_reg_edx_op2_reg_cl),
		TEST(shrd_op0_reg_ebx_op1_reg_dx_op2_reg_cl),
	};

	for (size_t i = 0; i < sizeof(tests) / sizeof(TestData); ++i)
	{
		asmjit::CodeHolder code;
		asmjit::X86Assembler a;
		code.init(asmjit::CodeInfo(asmjit::ArchInfo::kTypeX86));
		code.attach(&a);

		auto err = tests[i].gen(a);
		if (err != asmjit::kErrorOk)
		{
			printf("Error in %s: %d!\n", tests[i].name, (int)err);
		}
		else
		{
			code.sync();
			auto buf = code.getSectionEntry(0)->getBuffer().getData();
			auto size = code.getSectionEntry(0)->getBuffer().getLength();
			printf("%s:", tests[i].name);
			for (size_t i = 0; i < size; ++i)
				printf(" %02X", buf[i]);
			printf("\n");
		}
	}
}
```
Output:
```
bt_op0_reg_bx_op1_reg_edx: 0F A3 D3
bt_op0_reg_ebx_op1_reg_dx: 66 0F A3 D3
btc_op0_reg_bx_op1_reg_edx: 0F BB D3
btc_op0_reg_ebx_op1_reg_dx: 66 0F BB D3
btr_op0_reg_bx_op1_reg_edx: 0F B3 D3
btr_op0_reg_ebx_op1_reg_dx: 66 0F B3 D3
bts_op0_reg_bx_op1_reg_edx: 0F AB D3
bts_op0_reg_ebx_op1_reg_dx: 66 0F AB D3
imul_op0_reg_bx_op1_reg_edx_op2_simm_0000BBBB: 66 69 DA BB BB
imul_op0_reg_bx_op1_reg_edx_op2_simm_CCCCCCCC: 66 69 DA CC CC
imul_op0_reg_ebx_op1_reg_dx_op2_simm_0000BBBB: 69 DA BB BB 00 00
imul_op0_reg_ebx_op1_reg_dx_op2_simm_CCCCCCCC: 69 DA CC CC CC CC
imul_op0_reg_bx_op1_reg_edx_op2_simm_000000AA: 66 69 DA AA 00
imul_op0_reg_ebx_op1_reg_dx_op2_simm_000000AA: 69 DA AA 00 00 00
shld_op0_reg_bx_op1_reg_edx_op2_uimm_000000AA: 66 0F A4 D3 AA
shld_op0_reg_ebx_op1_reg_dx_op2_uimm_000000AA: 0F A4 D3 AA
shld_op0_reg_bx_op1_reg_edx_op2_reg_cl: 66 0F A5 D3
shld_op0_reg_ebx_op1_reg_dx_op2_reg_cl: 0F A5 D3
shrd_op0_reg_bx_op1_reg_edx_op2_uimm_000000AA: 66 0F AC D3 AA
shrd_op0_reg_ebx_op1_reg_dx_op2_uimm_000000AA: 0F AC D3 AA
shrd_op0_reg_bx_op1_reg_edx_op2_reg_cl: 66 0F AD D3
shrd_op0_reg_ebx_op1_reg_dx_op2_reg_cl: 0F AD D3
```
Actual disassembly of output:
```
bt ebx,edx
bt bx,dx
btc ebx,edx
btc bx,dx
btr ebx,edx
btr bx,dx
bts ebx,edx
bts bx,dx
imul bx,dx,BBBB
imul bx,dx,CCCC
imul ebx,edx,BBBB
imul ebx,edx,CCCCCCCC
imul bx,dx,AA
imul ebx,edx,AA
shld bx,dx,AA
shld ebx,edx,AA
shld bx,dx,cl
shld ebx,edx,cl
shrd bx,dx,AA
shrd ebx,edx,AA
shrd bx,dx,cl
shrd ebx,edx,cl
```

**Comment by kobalicek** [comment] 2018-12-06 10:39
Hello, this is a recurring issue.

AsmJit by default balances between performance and conformance by only checking register types when it's necessary for deciding about a correct encoding, so by default you get performance. However, it also provides a feature to turn on additional validation, which could be very handy for debugging:

```c++
// master - there is no API for this, however, you can turn it on this way:
assembler._globalOptions |= CodeEmitter::kOptionStrictValidation;

// next-wip
codeHolder.addEmitterOptions(BaseEmitter::kOptionStrictValidation);
```

Hope that helps and please note that in master branch this is officially unsupported feature. I would recommend using next-wip if you don't use the Compiler tool as that's the future of AsmJit and that's where new features are added at the moment.

**Comment by kobalicek** [comment] 2018-12-06 10:48
A possible duplicate of #21 #213

**Comment by mappzor** [comment] 2018-12-06 16:53
Thank you for reply. I didn't test next-wip branch yet but strict validation on master works great so far. All presented cases were properly handled. I also tried few hundreds of different tests with memory arguments and they all seem to be covered as well.

Usage of kErrorInvalidInstruction and kErrorOperandSizeMismatch seems to be a bit inconsistent sometimes but as long as any of them is reported I'm fine with it.

I'm still working on my full test set. When I finish I will run it against next-wip branch and let you know if I find anything that can bypass validation.

**Comment by kobalicek** [comment] 2018-12-06 17:43
Glad it's working for you. I think that reporting the correct error would need some additional work. The strict validation checks the exact signature and bails if it cannot find it, but I will think about having the error reporting closer to the actual issue (operand size, immediate size, etc).

I now recommend next-wip branch for new projects as the API is not backwards compatible, so you will save some future pain by using it now, but everybody has a choice and the old API will be moved to oldstable branch for projects that for some reason do not want to switch.

**Comment by kobalicek** [comment] 2019-07-16 07:42
Can I close this or is there still work to do?

**Closed** 2019-07-16 14:13 UTC
