### ISSUE TITLE
or with a 64 bit address fails?

### ISSUE THREAD

**Issue by MichaelRFairhurst** [asmjit/asmjit#154] opened 2017-02-16 03:42 UTC
This seems to fail in every variation:

```
    cc.or_(x86::word_ptr((uint64_t) &usage->argShapes[i]), checkReg.r16());
```

It fails regardless of the order of the operands, and regardless of size (qword and r64(), dword and r32, etc etc).

I tried to validate this behavior against the specification, but couldn't find anything about `or` and 64 bit addresses being a problem. Is it supposed to be allowed? Or is it in the spec (_somewhere_) that this isn't allowed?

**Comment by MichaelRFairhurst** [comment] 2017-02-16 04:08
I managed to work around the issue, but then after some refactoring of my ugly solution, got this:

```ERROR: Invalid use of 64-bit address: mov cx, word [+140556719095908]```

**Comment by kobalicek** [comment] 2017-02-16 09:22
The problem is that the instruction is unencodable. 64-bit addresses and immediates can only be used with MOV, all other instructions (even in 64-bit mode) use 32-bit immediates and sign extension.

The solution is to use temporary register instead:

```c++
cc.mov(tmp, (uint64_t)&usage->argShapes[i]);
cc.or_(x86::ptr(tmp), checkReg.r16());
```

NOTE: In 32-bit mode you can use any address as it would be encodable. AsmJit doesn't fix these by default as these are asm bugs, I think there is no assembler that automatically fixes these errors.

**Comment by kobalicek** [comment] 2017-02-19 18:42
Closing as it's not bug, let me know if you have any other issues

**Closed by kobalicek** 2017-02-19 18:42 UTC

**Comment by MichaelRFairhurst** [comment] 2017-02-19 21:47
Thanks. Like I said, couldn't find that in any specs but things like "xor" "register" and "64 bit" and "address" didn't seem to be good search terms :)

I'm guessing moving 64 bit values can only go into a 64 bit register as well? Regarding the issue with "mov cx ..."

**Comment by kobalicek** [comment] 2017-02-19 22:09
Well, it's important to differentiate between 64-bit address and 64-bit immediates. 64-bit operations are fine, but generally if you need 64-bit immediate value it's only supported by `mov`.

Check out this, it's instruction explorer I'm preparing:

  https://kobalicek.com/asmgrid/

And search for `iq` - that's quadword immediate, and then `id`, that's doubleword immediate, to get an idea about the possibilities.

And, 64-bit address is the same thing - it's not encodable, so moving the address to register first and then using the register is the common solution.

**Comment by MichaelRFairhurst** [comment] 2017-02-20 22:54
Awesome explorer! I will definitely use this!

I think I understand now. Looks like I should look more into effective addressing. I know that it (at least sometimes) supports an optional base address register, scale register, scale immediate value, and offset immediate value. I guess I was seeing that mem64 should be supported, and wrongly took that to mean that the offset portion of m64 could be 64 bit, which it can't. But the resulting value from reg + offset + reg2 * offset2 can be 64 bit, making it m64.

Really cool explorer, I will keep using this! Yet another awesome thing you've made for new players in the asm game like me. I truly appreciate everything you've done so much!
