### ISSUE TITLE
Assertion failure 

### ISSUE THREAD

**Issue by dibyendumajumdar** [asmjit/asmjit#168] opened 2017-04-09 02:10 UTC
Hi,

I am getting following assertion failure:
```
Error RAPass::livenessAnalysis() {

  ZoneList<CBNode*>::Link* retPtr = _returningList.getFirst();
  ASMJIT_ASSERT(retPtr != nullptr);
```

Any hints on what might be causing this?

My code is here:

https://github.com/dibyendumajumdar/dmr_c/blob/master/asmjit-backend/sparse-asmjit.cpp

Thanks and Regards
Dibyendu

**Comment by kobalicek** [comment] 2017-04-09 11:44
It seems a function has no return, thus liveness doesn't know where to start.

I know about this issue and I fixed it in next-wip branch, which is not yet complete. I'm not sure I want to fix this in current master as I would like to replace it with next-wip soon.

**Comment by dibyendumajumdar** [comment] 2017-04-09 11:50
Hi, there is a return instruction. There's no log output so I can't see what is happening unfortunately

**Comment by dibyendumajumdar** [comment] 2017-04-09 12:17
Just to give you some more background.

I am generation code for this simple C program:

https://github.com/dibyendumajumdar/dmr_c/blob/master/tests/nano/strlen.c

The intermediate IR from the front end looks like this:

https://github.com/dibyendumajumdar/dmr_c/blob/master/tests/nano/strlen.lin

My code takes this and generates instructions using X86Compiler. I can see the return being added if I step through each instruction.

**Comment by kobalicek** [comment] 2017-04-13 21:46
Just to add, I'm currently not focusing on these as I'm planning to replace the register allocator. I hope all issues like these would be fixed by design.

**Comment by dibyendumajumdar** [comment] 2017-04-13 21:51
Okay. Due to limited time I have not been able to submit the sequence of calls I am making - I was hoping to do this. But in the absence of logging support in CodeCompiler it is a bit of effort to do so. 

It would greatly help if some logging support was added to CodeCompiler. 

Is there a timescale for the new register allocator?

**Comment by kobalicek** [comment] 2017-04-13 21:55
Yeah there will be much better logging when it comes to CodeCompiler and its passes. I think these issues should be much easier to resolve. I would also like to have a way to be able to just use logs/dumps on my machine to test any function locally, which would help me with fixing bug reports quicker.

**Comment by kobalicek** [comment] 2017-04-13 21:56
BTW not really timescale, but I need just one more thing to implement to start testing it.

**Comment by dibyendumajumdar** [comment] 2017-04-13 22:03
Great! I am keen to implement as asmjit backend but I am relying on your register allocator rather than attempting to write one myself!

**Comment by dibyendumajumdar** [comment] 2017-07-06 19:54
hi @kobalicek , any news on the new version?
Thanks

**Comment by kobalicek** [comment] 2019-07-15 23:55
Closing as next-wip was merged.

**Closed by kobalicek** 2019-07-15 23:55 UTC
Labels: next-ready
